
#jedis配置信息
jedis:
  host: 192.168.0.108     # Redis服务器地址
  port: 6379              # Redis服务器连接端口
  #  password: 123456             # Redis服务器连接密码（默认为空）
  timeout: 0              # 连接超时时间（毫秒）
  pool:
    max-active: 200       # 连接池最大连接数
    max-wait: -1          # 连接池最大阻塞等待时间
    max-idle: 8           # 连接池中的最大空闲连接
    min_idle: 0           # 连接池中的最小空闲连接

#数据源配置
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.108:3306/ecai?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  # 映射文件所在路径
  mapper-locations: classpath*:com.code.dao.*/*.xml
  # pojo类所在包路径

  type-aliases-package: com.code.bean.pojo
  # 开启驼峰命名规则自动转换
  configuration:
    map-underscore-to-camel-case: true

#sql日志打印在控制台
logging:
  level:
    com:
      code: debug



